_OP_DEF(opexe_sam, "sam-contig",       1,  1,   TST_ANY,                               OP_SAM_CONTIG      )
_OP_DEF(opexe_sam, "sam-tid",       1,  1,   TST_ANY,                                  OP_SAM_TID      )
_OP_DEF(opexe_sam, "sam-read-name",       1,  1,   TST_ANY,                            OP_SAM_READ_NAME      )
_OP_DEF(opexe_sam, "sam-flag",       1,  1,   TST_ANY,                                 OP_SAM_FLAG      )
_OP_DEF(opexe_sam, "sam-has-flag?",       2,  2,   TST_ANY TST_INTEGER,                 OP_SAM_HAS_FLAG      )
_OP_DEF(opexe_sam, "sam-mapq",       1,  1,   TST_ANY,                                 OP_SAM_QUAL      )
_OP_DEF(opexe_sam, "sam-has-cigar?",       1,  1,   TST_ANY,                            OP_SAM_HAS_CIGAR      )
_OP_DEF(opexe_sam, "sam-cigar-string",       1,  1,   TST_ANY,                         OP_SAM_CIGAR_STR      )
_OP_DEF(opexe_sam, "sam-cigar-list",       1,  1,   TST_ANY,                         OP_SAM_CIGAR_LIST      )
_OP_DEF(opexe_sam, "sam-read-seq",       1,  1,   TST_ANY,                             OP_SAM_READSEQ      )
_OP_DEF(opexe_sam, "sam-read-qual",       1,  1,   TST_ANY,                             OP_SAM_READQUAL      )
_OP_DEF(opexe_sam, "sam-has-read-seq?",       1,  1,   TST_ANY,                         OP_SAM_HAS_READSEQ      )
_OP_DEF(opexe_sam, "sam-is-paired?",       1,  1,   TST_ANY,                         OP_SAM_IS_PAIRED      )
_OP_DEF(opexe_sam, "sam-is-proper-pair?",       1,  1,   TST_ANY,                         OP_SAM_IS_PROPER_PAIR      )
_OP_DEF(opexe_sam, "sam-read-unmapped?",       1,  1,   TST_ANY,                         OP_SAM_READ_UNMAPPED     )
_OP_DEF(opexe_sam, "sam-mate-unmapped?",       1,  1,   TST_ANY,                         OP_SAM_MATE_UNMAPPED     )
_OP_DEF(opexe_sam, "sam-read-reverse-strand?",       1,  1,   TST_ANY,                         OP_SAM_READ_REVERSE_STRAND     )
_OP_DEF(opexe_sam, "sam-mate-reverse-strand?",       1,  1,   TST_ANY,                         OP_SAM_MATE_REVERSE_STRAND     )
_OP_DEF(opexe_sam, "sam-rg-id",1,  1,   TST_ANY,                         OP_SAM_RG_ID     )

